### ISSUE TITLE
error self.backends[name].load()

### ISSUE THREAD

**Issue by czero69** [detectRecog/CCPD#17]
I got error in roi pooling for return self.backends[name].load(), while trying to run demo.py.
my env:

> CUDA 10.0
> Python 2.7.15 |Anaconda, Inc.
> >>> print(torch.__version__)
> 1.0.0

replacing 
 `self._backend = type2backend[type(input)] `with `self._backend = type2backend[input.type()]`
solved the problem

I suspect I have newer pytorch. See also: https://discuss.pytorch.org/t/keyerror-class-torch-tensor/22560

full error code:
`True
Traceback (most recent call last):
  File "demo.py", line 273, in <module>
    fps_pred, y_pred = model_conv(x)
  File "/home/kamil/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kamil/miniconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/kamil/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "demo.py", line 229, in forward
    roi1 = roi_pooling_ims(_x1, boxNew.mm(p1), size=(16, 8))
  File "/home/kamil/programy/CCPD/rpnet/roi_pooling.py", line 73, in roi_pooling_ims
    output.append(adaptive_max_pool(im, size))
  File "/home/kamil/programy/CCPD/rpnet/roi_pooling.py", line 35, in adaptive_max_pool
    return AdaptiveMaxPool2d(size[0], size[1])(input)
  File "/home/kamil/programy/CCPD/rpnet/roi_pooling.py", line 18, in forward
    self._backend = type2backend[type(input)]
  File "/home/kamil/miniconda2/lib/python2.7/site-packages/torch/_thnn/__init__.py", line 15, in __getitem__
    return self.backends[name].load()
KeyError: <class 'torch.Tensor'>`

**Comment by czero69** [comment]
> replacing
> self._backend = type2backend[type(input)] with self._backend = type2backend[input.type()]
> solved the problem

**Comment by Moriarty12138** [comment]
Ty

**Comment by Moriarty12138** [comment]
Ty

**Comment by ww451575464** [comment]
thanks

**Comment by liuqc11** [comment]
thanks

**Comment by Fansgithub2019** [comment]
Did it like you did, but there was a new error.

True
Traceback (most recent call last):
  File "demo.py", line 275, in <module>
    fps_pred, y_pred = model_conv(x)
  File "/home/fan/anaconda3/envs/tf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fan/anaconda3/envs/tf/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/fan/anaconda3/envs/tf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "demo.py", line 230, in forward
    roi1 = roi_pooling_ims(_x1, boxNew.mm(p1), size=(16, 8))
  File "/home/fan/CCPD-master/rpnet/roi_pooling.py", line 74, in roi_pooling_ims
    output.append(adaptive_max_pool(im, size))
  File "/home/fan/CCPD-master/rpnet/roi_pooling.py", line 36, in adaptive_max_pool
    return AdaptiveMaxPool2d(size[0], size[1])(input)
  File "/home/fan/CCPD-master/rpnet/roi_pooling.py", line 20, in forward
    self._backend.SpatialAdaptiveMaxPooling_updateOutput(
  File "/home/fan/anaconda3/envs/tf/lib/python3.7/site-packages/torch/_thnn/utils.py", line 27, in __getattr__
    raise NotImplementedError
NotImplementedError

Is this the need to define the subclass SpatialAdaptiveMaxPooling_updateOutput?
Could anybody help me?

**Comment by ggsggs** [comment]
I also have the same problem with Pytorch 1.1 and Windows. Perhaps downgrading to pytorch 0.4 solves the problem.

**Comment by Fansgithub2019** [comment]
How to downgrade to pytorch 0.4?Remove  Pytorch 1.1 and install pytorch 0.4 ?

**Comment by ggsggs** [comment]
I am not the best person to recommend but:
I would create a new virtual environment and install all required packages.

If you are using conda, `conda create - n yourenvname python=x.x
source activate yourenvname` and then install all packages you need with
conda install yourpackage1

And then install the pytorch version that are used in this repo.
