### ISSUE TITLE
when training rpnet, division by zero

### ISSUE THREAD

**Issue by Doylegyf** [detectRecog/CCPD#36]
Traceback (most recent call last):
  File "rpnet.py", line 405, in <module>
    model_conv = train_model(model_conv, criterion, optimizer_conv, num_epochs=epochs)
  File "rpnet.py", line 395, in train_model
    print ('%s %s %s\n' % (epoch, sum(lossAver) / len(lossAver), time()-start))
ZeroDivisionError: division by zero

It seems lossAver=0.Has anyone encountered such a problem?

**Comment by Doylegyf** [comment]
Maybe it is because the wr2 network training is not good enough?

**Comment by Doylegyf** [comment]
The reason is loss.data[0],I changed it to loss.item()

**Comment by zhqx511** [comment]
Yes，you are right，just because of the torch version

**Comment by loyneshunter** [comment]
@Doylegyf  I also encountered this problem...I use your method to modify the code.The output is NAN.Do you know why.Thank you！

**Comment by Yifanzhou-0713** [comment]
Same problem. Seems wR2 doesn't own 'model' attribute?
Have you solved the problem?
